services:
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../client/build:/usr/share/nginx/html
      - ./production/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
      - DB_PORT=3306
      - DB_HOST=db

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - portfolio-havanduoc-mysql-data:/var/lib/mysql
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: havanduoc
    expose:
      - 3306

volumes:
  portfolio-havanduoc-mysql-data:

    # docker compose -p portfolio up -d
